### ISSUE TITLE
More fonts or google fonts

### ISSUE THREAD

**Issue by uche40** [viliusle/miniPaint#107] opened 2018-06-03 17:57 UTC
Hey Great app. But very limited text fonts. How do i add more fonts or can you integrate google fonts in the next update. Thanks

**Comment by viliusle** [comment] 2018-06-03 19:09
Hey,
Yes, its limited, will add this to Todo list.

**Comment by uche40** [comment] 2018-06-04 20:47
Ok cool, will be waiting on next update. And by the way, the text editing options section is way too hidden and hard to get to, on the lower right corner, consider moving it up .

**Comment by viliusle** [comment] 2018-06-17 19:12
Closing, because its duplicate of #99.

**Closed by viliusle** 2018-06-17 19:12 UTC
